namespace: production
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
secretGenerator:
- files:
  - .dockerconfigjson
  name: regcred
  type: kubernetes.io/dockerconfigjson
commonLabels:
  app.kubernetes.io/name: dockerhub-eks-clj-web
images:
- name: slimslenderslacks/dockerhub-eks-clj-web
  newTag: v1-1-g70306a6
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
