namespace: production
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- regcred.yaml
- ingress.yaml
commonLabels:
  app.kubernetes.io/name: dockerhub-eks-clj-web
images:
- name: slimslenderslacks/dockerhub-eks-clj-web
  newTag: v24
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
decryption:
  provider: sops
  secretRef:
    name: sops-gpg
